# base image
FROM node:12.2.0-alpine

# set working directory
WORKDIR /Users/Global/Documents/GitHub/Rabigithub/Devops/tcsdevops

# add `/app/node_modules/.bin` to $PATH
ENV PATH /Users/Global/Documents/GitHub/Rabigithub/Devops/tcsdevops/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /Users/Global/Documents/GitHub/Rabigithub/Devops/tcsdevops/package.json
RUN npm install --silent
RUN npm install react-scripts@3.0.1 -g --silent

# start app
CMD ["npm", "start"]